#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<time.h>
#include<unistd.h>
int main()
{
    int length;
    printf("\n enter the password length: ");
    scanf("%d",&length);

    if(length<=0)
    {
        printf("\n password length must be greater than equal to 1");
        return 1;
    }

    char *password=malloc(length+1);
    char *digits="0123456789";
    int digit_length=strlen(digits);
    char *lowers="abcdefgghijklmnopqrstuvwxyz";
    int lower_length=strlen(lowers);
    char *upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    int upper_length=strlen(upper);
    char *symbols="!@#$%^&*()";
    int symbol_length=strlen(symbols);

    //for multyply each unique time with rand number generated by getpid()
    srand(time(NULL)*getpid());

    int i;
    int char_type;
    for(i=0;i<length;i++)
    {
        char_type=rand()%4;

        if(char_type==0)
            password[i]=digits[rand()%digit_length];
        else if(char_type==1)
            password[i]=lowers[rand()%lower_length];
        else if(char_type==2)
            password[i]=upper[rand()%upper_length];
        else if(char_type==3)
            password[i]=symbols[rand()%symbol_length];

    }
    password[length]='\0';
    printf("\n the password is: ");
    puts(password);
    free(password);

    return 0;

}